apiVersion: apps/v1
kind: Deployment
metadata:
  name: notelify-article
  labels: 
    app: notelify-article
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: notelify-article
  template:
    metadata:
      labels: 
        app: notelify-article
    spec:
      containers:
        - name : notelify-article
          image: antonyinjila/notelify-articles-service:latest
          ports:
            - containerPort: 8001
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: notelify-secret
                  key: aws_access_key

            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notelify-secret
                  key: aws_secret_key

            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: notelify-secret
                  key: secret_key

            - name: AWS_DEFAULT_REGION
              valueFrom:
                configMapKeyRef:
                  name: notelify-config
                  key: aws_default_region

            - name: DatabaseHost
              valueFrom:
                configMapKeyRef:
                  name: notelify-config
                  key: database_host
                  
            - name: RDSInstanceIdentifier
              valueFrom:
                configMapKeyRef:
                  name: notelify-config
                  key: rds_instance_identifier

---
apiVersion: v1
kind: Service
metadata:
  name: notelify-articles-service
spec:
  type: ClusterIP
  selector:
    app: notelify-article
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
  



