apiVersion: v1
kind: Secret
metadata:
  name: notelify-secret
type: Opaque
data:
  aws_access_key: QUtJQVZDUjJGSlJNTkpSVlo0NTc=
  aws_secret_key: Vm1lWkxmdGc1cmhpV05JVXZIWjhSTk15NUVqTVByMFF5bWxWYkpmQQ==
  database_password: cGFzczEyMzQ=
  secret_key: dG9wc2VjcmV0



