# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Push to Docker
      env:
        AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        DatabasePassword: ${{ secrets.DatabasePassword }}
        DatabaseUser: ${{ secrets.DatabaseUser }}
        DatabaseHost: ${{ secrets.DatabaseHost }}
        LoggerURL: ${{ secrets.LoggerURL }}
        RDSInstanceIdentifier: ${{ secrets.RDSInstanceIdentifier }}
        
      uses: mr-smithers-excellent/docker-build-push@v6
      with:
        image: antonyinjila/notelify-articles-service
        tags: latest
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name : Push to AWS ECR
    - uses: actions/checkout@v2
    - uses: docker://ghcr.io/kciter/aws-ecr-action:latest
      with:
        access_key_id: ${{ secrets.AWS_ACCESS_KEY }}
        secret_access_key: ${{ secrets.AWS_SECRET_KEY }}
        account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        repo: notelify-articles-svc-ecr
        region: me-south-1
        tags: latest
        create_repo: true
        image_scanning_configuration: true
        set_repo_policy: true
        repo_policy_file: repo-policy.json
          
     
          
